### ISSUE TITLE
Todo list from June `14 BLD question

### ISSUE THREAD

**Issue by Technical-13** [wikimedia-gadgets/afc-helper#18]
Based on [this original discussion](http://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation/June_2014_Backlog_Elimination_Drive#A_pat_on_your_backs_and_Request_for_Comments):
- [ ] Should call and support the existing working FFU and AFC/R scripts. See: #15 
- [x] Should offer more user customizable preferences
  *\* and possibly a better way to store these preferences
- [x] Should offer a way to disable the script from the script. See:  #17
- [ ] Should offer a better way to report bugs and request features.
- [ ] Should offer a simple interface to be able to switch versions for testers. See: #16
- [x] The submitter talk page decline notification should include the decline reason.
- [ ] Posting the user talk page notification should offer to post a "Welcome!" message as well as the Teahouse notification. See: #45
- [x] Allow multiple decline reasons. (EG. v and adv in the same template) See: #78 
- [ ] Offer an option to automatically move declined userspace drafts to Draft space
- [ ] Better SALTed (or otherwise inaccessible) title handling per [this discussion](http://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation/Helper_script/Rewrite#.5B0.8.5D_Feedback_about_create-protection).
- [ ] Inject a comment into the wikitext right above the categories when taking draft out of categories in cleanup explaining drafts do not go in content categories until accepted.
- [ ] For a BLP, {{Wikiproject Biography}} must always be the on 'top' (see http://en.wikipedia.org/wiki/Wikipedia:Talk_page_layout#Lead_.28bannerspace.29), and the script should detect when to use {{WikiProjectBannerShell}} and {{WikiProjectBanners}}.
- [ ] Script fails to know when DEFAULTSORT and PERSONDATA are already in the draft and adds another one.
- [ ] Cleaning to remove a mainspace category put the AfC header above {{csb-pageincludes}}. see http://en.wikipedia.org/w/index.php?title=Draft:Dogtag&diff=615200212&oldid=615219993

I think this covers the list for (semi-)script related stuff for now.  Will update if more ideas come in.

**Comment by NovemLinguae** [comment]
Closing for now. If any of these are not stale, should probably be remake as individual tickets.
